version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: cinema-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: onlinebooking_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: cinema-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cinema-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  nacos:
    image: nacos/nacos-server:v2.4.3  # 强烈建议锁死版本，不要用 latest
    container_name: cinema-nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - NACOS_AUTH_TOKEN=U2VjcmV0S2V5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5
      - NACOS_AUTH_IDENTITY_KEY=example
      - NACOS_AUTH_IDENTITY_VALUE=example
      # ▼▼▼【关键修复 2】限制内存为 256M，防止电脑卡死 ▼▼▼
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_XMN=128m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: always

volumes:
  mysql_data:
  nacos_logs:
  nacos_data: