version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: cinema-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./online-booking-system/dist:/usr/share/nginx/html:ro
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge