# 文件名：Dockerfile.membership (位于项目根目录)
# 阶段 1: 构建阶段
FROM maven:3.8-openjdk-17 AS build
WORKDIR /app

# 1. 复制整个项目到容器的 /app/ 目录 (现在 context 是根目录，所以可以复制所有内容)
COPY . /app/

# 添加这行，将根目录下的 setting.xml 复制到 Maven 的标准配置目录
# Dockerfile 中的路径是相对于构建上下文（根目录）的
COPY setting.xml /usr/share/maven/ref/setting.xml
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY prometheus.yml /etc/prometheus/prometheus.yml

# 2. 切换到当前模块的目录
# 关键步骤：必须在模块目录下执行 package 命令
WORKDIR /app/old_project

# 3. 编译和打包当前模块
# Maven 此时能找到 /app/ 目录下的父 POM 文件
RUN mvn clean package -Dmaven.test.skip=true -s /usr/share/maven/ref/setting.xml

# 阶段 2: 运行阶段
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
# 复制构建好的jar文件 (注意路径：是从构建阶段的 /app/old_project 目录下复制)
COPY --from=build /app/old_project/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]