server:
  port: 8081  # 使用不同的端口

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://desktop-7nla9nf.taila5d3f3.ts.net:3306/onlinebooking_system
    username: root
    password: '123456'

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.zzu.membership.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
